### ISSUE TITLE
[Bug]: New Inverter X3 G4 Pro - unrecognized inverter type

### ISSUE THREAD

**Issue by krauseck** [wills106/homeassistant-solax-modbus#1380]
### Describe the bug

I have the new Solax Inverter X3 G4 Pro and the Plugin is not able to recognize the inverter type. 

Info from Solax,support: the modbus protocol/properties are the same like the old X3 G4.

### Integration Version

2025.04.4

### Homeassistant core version

2025.5.2

### Inverter brand

Solax Power

### Plugin used

plugin_solax.py

### Serial prefix

10K0A1

### Inverter firmware versions

006.09-000.06

### Connection Method

latest Solax Wifi/LAN dongle

### Dongle firmware

1.005.04

### Detailed Error Log

2025-05-21 18:49:30.648 INFO (MainThread) [custom_components.solax_modbus.plugin_solax] SolaX: trying to determine inverter type
2025-05-21 18:49:30.696 INFO (MainThread) [custom_components.solax_modbus.plugin_solax] Read SolaX 0x0 serial number: XXXXXX (deleted my serial)
2025-05-21 18:49:30.696 ERROR (MainThread) [custom_components.solax_modbus.plugin_solax] unrecognized inverter type - serial number : XXXXXX (deleted my serial)

**Comment by wills106** [comment]
@krauseck Did you get this working by just adding in your Serial? Or is further work needed?

**Comment by krauseck** [comment]
sorry, i closed this issue by myself because i have seen this to late: **https://github.com/wills106/homeassistant-solax-modbus/discussions/520?sort=new**

After closing here, I added a comment in the discussion. I have no solution for this problem. were i am able to adding in my Serial?

**Comment by wills106** [comment]
I have released [2025.06.2](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2025.06.2) with Initial support for these new Inverters.

I have guessed some of the registers as the doc listed [here](https://github.com/wills106/homeassistant-solax-modbus/discussions/520#discussioncomment-13235344) seems to be missing some basic registers.

If anything key seems missing try updating the following:
(plugin_solax.py)

`allowedtypes=AC | HYBRID | GEN4 | GEN5,` to `allowedtypes=AC | HYBRID | GEN4 | GEN5 | GEN6,`

`allowedtypes=AC | HYBRID | GEN5,` to `allowedtypes=AC | HYBRID | GEN5 | GEN6,`

**Comment by 61samuel** [comment]
Hello
I am still having the same problem as before update, "unrecognized inverter type - serial number"
Solax x3-hyb-G4 Pro 15KW
Communication should be good cuz it finds my serial number.

**Comment by 61samuel** [comment]
Forgott to add serial number, 10K0F1

**Comment by KKeXX** [comment]
Hi,

I've a X3-HYB-G4 PRO  as @61samuel. s/n starts with 10K0F. I've inserted the s/n `(seriesnumber.startswith("10K0F"))`  into plugin_solax.py, then the Inverter is found. But there seem to be registers missing..

@wills106, what values should be updated, as you mentioned [here](https://github.com/wills106/homeassistant-solax-modbus/issues/1380#issuecomment-3003760104)

Thanks.

**Comment by InToSSH** [comment]
@wills106 Hi, apart from the scaling issue still present mentioned [here](https://github.com/wills106/homeassistant-solax-modbus/issues/1562#issuecomment-3234902325), would it also please be possible to change the max value for "Battery Charge Max Current"? It is currently 20A, but the inverter actually allows up to 50A. This way if I change it, I have to go to the Solax app to change it back.
