### ISSUE TITLE
[Bug]: Inverter connection lost after upgrade to 2025.05.3

### ISSUE THREAD

**Issue by ezfrag2021** [wills106/homeassistant-solax-modbus#1404]
### Describe the bug

All entities unavailable after update to latest version.

### Integration Version

2025.05.3

### Homeassistant core version

2025.5.3

### Inverter brand

Solax

### Plugin used

plugin_solax.py

### Serial prefix

H3DE05

### Inverter firmware versions

Unknown

### Connection Method

Ethernet

### Dongle firmware

2.034.03

### Detailed Error Log

This error originated from a custom integration.

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:725
integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 07:35:19 (6 occurrences)
Last logged: 07:47:34

ModbusIOError: Modbus Error: [Input/Output] Modbus value 5 not found in scale mapping for meter_1_direction

**Comment by ezfrag2021** [comment]
Rolling back the integration version to 2025.05.2 or 2025.05.01 did not fix the issue. Problem may be due to upgrade of HA Core.

Edit: rolled back to the backup from Saturday and the problem is resolved so no idea what caused it.

**Comment by godfreym29** [comment]
I'm also seeing this

**Detailed Error Log**
This error originated from a custom integration.

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:725
integration: SolaX Inverter Modbus (documentation, issues)
First occurred: 10:10:59 (8 occurrences)
Last logged: 10:28:14

ModbusIOError: Modbus Error: [Input/Output] Modbus value 48 not found in scale mapping for backflow_power_switch


also getting a lot of these errors in the log


```
2025-06-01 10:33:48.986 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.solis_battery_charge_current for domain sensor with platform solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 979, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 259, in async_internal_added_to_hass
    raise HomeAssistantError(
        f"Entity {self.entity_id} cannot be added as the entity category is set to config"
    )
homeassistant.exceptions.HomeAssistantError: Entity sensor.solis_battery_charge_current cannot be added as the entity category is set to config
2025-06-01 10:33:48.987 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.solis_battery_discharge_current for domain sensor with platform solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 979, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 259, in async_internal_added_to_hass
    raise HomeAssistantError(
        f"Entity {self.entity_id} cannot be added as the entity category is set to config"
    )
homeassistant.exceptions.HomeAssistantError: Entity sensor.solis_battery_discharge_current cannot be added as the entity category is set to config
2025-06-01 10:33:48.988 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.solis_timed_charge_current for domain sensor with platform solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 979, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 259, in async_internal_added_to_hass
    raise HomeAssistantError(
        f"Entity {self.entity_id} cannot be added as the entity category is set to config"
    )
homeassistant.exceptions.HomeAssistantError: Entity sensor.solis_timed_charge_current cannot be added as the entity category is set to config
2025-06-01 10:33:48.989 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity sensor.solis_timed_discharge_current for domain sensor with platform solax_modbus
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 979, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1368, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 259, in async_internal_added_to_hass
    raise HomeAssistantError(
        f"Entity {self.entity_id} cannot be added as the entity category is set to config"
    )
homeassistant.exceptions.HomeAssistantError: Entity sensor.solis_timed_discharge_current cannot be added as the entity category is set to config
```

**Comment by MkVsM** [comment]
The same problem with Solax X3 Hybrid G1/G2 via LAN. It work only 2025.05.1.

**Comment by decibelhuis** [comment]
The same problem with solis rhi-3p10k-hves-5g via LAN. It work with 2025.05.01

**Comment by pksoft585** [comment]
The same problem with Solax X3-Hybrid G3 via LAN. It work with 2025.05.01

**Comment by felixhix** [comment]
Have a similar issue since Update to 2025.5.3 but with Growatt Inverter.
```
Logger: custom_components.solax_modbus
Quelle: custom_components/solax_modbus/__init__.py:725
Integration: SolaX Inverter Modbus (Dokumentation, Probleme)
...
ModbusIOError: Modbus Error: [Input/Output] Modbus value 5 not found in scale mapping for grid_first_time_6
```

**Comment by azeair** [comment]
Same here.

**Comment by TommasoPino** [comment]
I think it is the same error. It happens after a restart of hassio

Registratore: custom_components.solax_modbus.plugin_sofar
Fonte: custom_components/solax_modbus/plugin_sofar.py:4161
Integrazione: SolaX Inverter Modbus (documentazione, problemi)
Prima occorrenza: 14:23:22 (1 occorrenza)
Ultimo accesso: 14:23:22

unrecognized ZCS2 inverter type - serial number : unknown

**Comment by wills106** [comment]
Has this been resolved now in later releases?

**Comment by felixhix** [comment]
I can confirm that entities will appear normally again with version 2025.08.7.

**Comment by felixhix** [comment]
Unfortunately I have to take back my statement, some entities have ‘come back’, but some values are still missing compared to the ‘stable’ version.

These are in particular:
- Today's Solar Energy
- Grid Power L2+L3
- AC Power to User Total

**Comment by infradom** [comment]
@felixhix : unsufficient info, no model info, no debug logfile, no HA verson. 
ignoring ...

**Comment by felixhix** [comment]
Sorry for that 😄 :
- HA: 2025.8.3
- Inverter: Growatt SPH 10k TL3-BH UP
- Solax: 2025.08.7

Solax Log-Level is currently at INFO. Will switch it to DEBUG.

**Comment by felixhix** [comment]
See attached log file. Is it sufficient?

[ha-solax-growatt-issue_1404.log](https://github.com/user-attachments/files/22057908/ha-solax-growatt-issue_1404.log)

**Comment by wills106** [comment]
When starting up HA is the Inverter recognised as YA1?

Edit:
There should be a comment in your log like:

`firmware number before potential swap: YA1`

**Comment by felixhix** [comment]
Yes, see log:
`2025-08-30 11:58:20.495 INFO (MainThread) [custom_components.solax_modbus.plugin_growatt] Growatt: trying to determine inverter type
2025-08-30 11:58:20.585 INFO (MainThread) [custom_components.solax_modbus.plugin_growatt] Read Growatt 0x9 firmware number before potential swap: YA1.0ZDAA`.

This matches with the informations from the Growatt webportal:

<img width="349" height="256" alt="Image" src="https://github.com/user-attachments/assets/88568115-3fbf-49fd-adb8-2c6b229a9383" />

**Comment by felixhix** [comment]
Just to make an observation: It is conspicuous that the respective ‘* Todays Total’ entities are frequently affected.

**Comment by infradom** [comment]
> When starting up HA is the Inverter recognised as YA1?
> 
> Edit: There should be a comment in your log like:
> 
> `firmware number before potential swap: YA1`

This has already been treated in a growatt related issue thread: short summary: 
Today's solar energy is compauted as: 
```
return  datadict.get('today_s_pv1_solar_energy', 0) + datadict.get('today_s_pv2_solar_energy',0) + datadict.get('today_s_pv3_solar_energy',0) + datadict.get('today_s_pv4_solar_energy',0)
```
So the 4 underlying entities should be enabled manually for now (until the planned dependency mechanism for sensors is in place)

Similar for grid_power_:
```
return  datadict.get('grid_power_l1', 0) + datadict.get('grid_power_l2', 0) + datadict.get('grid_power_l3', 0)
```
The underlying entities grid_power_lXXX must be enabled manually for now (until someone updates the plugin_growatt.py file) or until the dependency mechanism is in place. 

Ac_power_to_user_total seems to be a different issue, but certainly for this thread

**Comment by infradom** [comment]
Please report your problems in a dedicated thread
(most of them have already been discussed)
As far as I can see, this discussion has nothing to do with the original issue discussed here

**Comment by infradom** [comment]
I have explained the disabled entities problem multiple times in other isssue threads, The quickfix is to enable the underlying register entities

**Comment by felixhix** [comment]
Thanks for the clarification. I have activated it and the value is now calculated. Just a side note: The SPH only has 2 MPP trackers. Isn't it actually the case that the SPH has its own register for the Today ‘Total’? I may be wrong, though.
Growatt Documentation: https://community.symcon.de/uploads/short-url/jFo2xrUpTus03y9fWeYrp0Dbfng.pdf

**Comment by infradom** [comment]
> Just a side note: ...

Thanks for the feedback, but if you want the note to be read and treated, it is better to open a separate issue  (which makes sense in my opinion). And please put growatt in the title. 
It deserves a separate issue thread. ignoring it here
