### ISSUE TITLE
Solax - After update to 2025.8.1/2 values are updated very slow, almost every minute.

### ISSUE THREAD

**Issue by itrankolov** [wills106/homeassistant-solax-modbus#1548]
I also have this in HA logs:

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:829
integration: SolaX Inverter Modbus ([documentation](https://homeassistant-solax-modbus.readthedocs.io/), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 10:40:43 AM (2 occurrences)
Last logged: 10:41:33 AM

Something went wrong reading from modbus: Attribute hass is None for <entity unknown.unknown=unknown>
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 829, in async_read_modbus_data
    res = await self.async_read_modbus_registers_all(group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 1056, in async_read_modbus_registers_all
    if sens and not descr.internal: sens.modbus_data_updated() # publish state to GUI and automations faster
                                    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solax_modbus/sensor.py", line 249, in modbus_data_updated
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_verify_state_writable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>

**Comment by infradom** [comment]
Missing information: which inverter brand/model, are we talking about the HA version or of the integration version ?
No full debug log ...
Ignoring for now ...

**Comment by itrankolov** [comment]
Sorry for the missing info, I was in a hurry in the morning. 
Inverter: Solax X3-Ultra-30kW
HA: 2025.8.2
Integration: 2025.08.2

Currently I cannot share full logs, because I rolled back the integration to 2025.07.7. I will update again and try to provide more detailed logs later today.

**Comment by itrankolov** [comment]
Here is a debug log:

[home-assistant_solax_modbus_2025-08-20T12-05-55.344Z.log](https://github.com/user-attachments/files/21893752/home-assistant_solax_modbus_2025-08-20T12-05-55.344Z.log)

**Comment by infradom** [comment]
Thanks for the logfile. It will certainly help - I need some time since there are a couple of other bugs requiring attention .. 
Then I will upgrade my HA to the same version you have and see if the error then also occurs on my system.

**Comment by itrankolov** [comment]
If it will be in any help - I can report, that the issue is not present with Solax X3-Hybrid-15kW and X3-Ultra-20kW
 with the same HA and integration versions (2025.8.2), but it is another HA instance, so it may be related to my HA install or inverter firmware version, but I have no idea how to check that.

**Comment by infradom** [comment]
I just upgraded my system to HA 2025.8.2 and cannot reproduce your problem on my system.
The error in the logs looks very strange, at the time of writing, I have no direct clue what is causing this ...

**Comment by itrankolov** [comment]
This "Attribute hass is None for <entity unknown.unknown=unknown>" bothers me - is this the entity in HA? Is there a possibility that something is disabled like a sensor or so and that is why it does it ?

**Comment by infradom** [comment]
It does not seem to be related to a disabled sensor as far as I can see.  It is very unlike the issues with disabled sensors.
But I need to give it some more thought. I might need to add some more debug output to find out what sensor update has the missing hass link. Would you be able to test with a source file that contains more debug output or are you not familiar with adapting individual source files ?

**Comment by itrankolov** [comment]
No, I'm not, but if you guide me, or point me to the documentation that describes how to do that, I will be able to do it.

**Comment by itrankolov** [comment]
By "test with a soruce file" do you mean changing some file in here: /config/custom_components/solax_modbus ?

**Comment by gernotgernot** [comment]
Same error here:

Solax Hybrid X3 G4 inverter. 
Homeassistant speaking over modbus tcp with Solax Wifi+LAN Dongle (connected over LAN) with modbus proxy (homeassitant) between.

Error:

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:829
integration: SolaX Inverter Modbus ([documentation](https://homeassistant-solax-modbus.readthedocs.io/), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: August 19, 2025 at 11:03:47 PM (1169 occurrences)
Last logged: 1:59:50 PM

Something went wrong reading from modbus: Attribute hass is None for <entity unknown.unknown=unknown>
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 829, in async_read_modbus_data
    res = await self.async_read_modbus_registers_all(group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 1056, in async_read_modbus_registers_all
    if sens and not descr.internal: sens.modbus_data_updated() # publish state to GUI and automations faster
                                    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solax_modbus/sensor.py", line 249, in modbus_data_updated
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_verify_state_writable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>


I have seen some py829 error several times before, but it was always everything working, so i never bothered about them.
Still, this time the same, error is written in log, but as far as i can see everything seems to work fine.
(i was using 2025.8.2, just updated to .3)

**Comment by itrankolov** [comment]
In my case I figured out there is an issue because HA updates values every 1m or so, not 5s. Can you check the update rate of your sensors ?

**Comment by infradom** [comment]
> By "test with a soruce file" do you mean changing some file in here: /config/custom_components/solax_modbus ?

yes, this is what I meant, I would tell you which lines to change

**Comment by infradom** [comment]
This is probably  because the system believes your system is in sleep mode after the communication error. When the integration thinks the system is in sleep mode, it will poll the registers at a 10 times slower speed. There was a good reason for that, but I cannot remember for now.
Anyway, we should find the root cause and avoid that the system believes the inverter is in sleep mode

**Comment by gernotgernot** [comment]
> In my case I figured out there is an issue because HA updates values every 1m or so, not 5s. Can you check the update rate of your sensors ?

i have some data that shows 12 seconds interval (my normal interval), but also some times very i only see updates every 45 to 120 sconds..... might be the sleep mode that infradom mentioned.

**Comment by infradom** [comment]
If you could modify the source code of `__init__.py` 
On line 1055 (approx) you will see: 
```
            #_LOGGER.debug(f"quickly updating state for computed sensor {sens} {key} {data[descr.key]} "
```
could you remove the # sign from that line so that there is extra debug output . Attention: in python blanks matter, do not add or remove any blanks (space characters)

advice: make a copy of the file first so that you can restore if something goes wrong

**Comment by gernotgernot** [comment]
additional info:

after updating to .3 same error and another one (see other error after the original one in this post)

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:829
integration: SolaX Inverter Modbus ([documentation](https://homeassistant-solax-modbus.readthedocs.io/), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 2:09:58 PM (20 occurrences)
Last logged: 2:47:46 PM

Something went wrong reading from modbus: Attribute hass is None for <entity unknown.unknown=unknown>
Traceback (most recent call last):
  File "/config/custom_components/solax_modbus/__init__.py", line 829, in async_read_modbus_data
    res = await self.async_read_modbus_registers_all(group)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solax_modbus/__init__.py", line 1056, in async_read_modbus_registers_all
    if sens and not descr.internal: sens.modbus_data_updated() # publish state to GUI and automations faster
                                    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/solax_modbus/sensor.py", line 249, in modbus_data_updated
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_verify_state_writable()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 987, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>



and another error is appearing two, don't know if that information helps:

Logger: homeassistant
Source: components/sensor/__init__.py:670
First occurred: 2:10:15 PM (77 occurrences)
Last logged: 2:48:15 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 663, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'null'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 666, in state
    numerical_value = float(value)
ValueError: could not convert string to float: 'null'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1140, in _async_update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 981, in async_update_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1151, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1088, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1032, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 670, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.openwb_vehicle_0_reichweite has device class 'None', state class 'measurement' unit 'km' and suggested precision '0' thus indicating it has a numeric value; however, it has the non-numeric value: 'null' (<class 'str'>)

will add the line soon and give you feedback

**Comment by infradom** [comment]
> will add the line soon and give you feedback

Thanks, I will need a full debug log then, not only the error lines

**Comment by itrankolov** [comment]
[home-assistant_solax_modbus_2025-08-21T13-00-12.279Z.log](https://github.com/user-attachments/files/21918291/home-assistant_solax_modbus_2025-08-21T13-00-12.279Z.log)

2025-08-21 15:58:28.228 DEBUG (MainThread) [custom_components.solax_modbus] quickly updating state for computed sensor <entity unknown.unknown=unknown> remotecontrol_autorepeat_remaining 0

**Comment by gernotgernot** [comment]
ok, i have added the line and restartet homeassistant. error is back. can you please help me how to create the full debug of the HACS solax modbus integration?

EDIT:

just found it in the documentation: https://homeassistant-solax-modbus.readthedocs.io/en/latest/faq/#produce-a-debug-log-file-with-startup-info

**Comment by infradom** [comment]
> 2025-08-21 15:58:28.228 DEBUG (MainThread) [custom_components.solax_modbus] quickly updating state for computed sensor remotecontrol_autorepeat_remaining 0

Ok, thanks, this will lead us to a solution !!

**Comment by gernotgernot** [comment]
Here is the debug log:

errors are shown in home assistant core log at 3:05:39 PM and 3:07:00 PM

[home-assistant_solax_modbus_2025-08-21T13-04-49.532Z.log](https://github.com/user-attachments/files/21918400/home-assistant_solax_modbus_2025-08-21T13-04-49.532Z.log)

**Comment by infradom** [comment]
> errors are shown in home assistant core log at 3:05:39 PM and 3:07:00 PM
> 
> [home-assistant_solax_modbus_2025-08-21T13-04-49.532Z.log](https://github.com/user-attachments/files/21918400/home-assistant_solax_modbus_2025-08-21T13-04-49.532Z.log)

Perfect ! same entity fails. I am working on the solution now. Thanks a lot for your help

**Comment by infradom** [comment]
Finding a solution is not as easy as I thought, it is unclear why this computed entity performs differently than the other ones. Still searching ...
I also dont understand why this does not happen on all systems.

**Comment by infradom** [comment]
This should temporarily fix the slowdown but it does not solve the root cause: (line 1055 in `__init__.py`
```
            #_LOGGER.debug(f"quickly updating state for computed sensor {sens} {key} {data[descr.key]} ")
            try: 
                if sens and not descr.internal: sens.modbus_data_updated() # publish state to GUI and automations faster
            except: # temporary for issue #1548
                 _LOGGER.error(f"quickly updating state for computed sensor failed {sens} {key} {data[descr.key]} ")

```

**Comment by gernotgernot** [comment]
Thanks for your work, if I can do anything to help please ask.
additional information if needed:

Home Assistant

Installation method
Home Assistant OS
Core
2025.8.2
Supervisor
2025.08.1
Operating System
16.0
Frontend
20250811.0

Inverter: 

Device info
X3-Hybrid-15kW
by SolaX Power
Firmware: DSP v1.51 ARM v1.49
Hardware: Gen4

**Comment by infradom** [comment]
> if I can do anything to help please ask.


Thanks
Have you tried the temporary fix code I suggested? Does it work?
If so, we can make a new release and wait until we understand better the root cause.

**Comment by gernotgernot** [comment]
After applying the code and restarting HA i get error in the log:

Logger: custom_components.solax_modbus
Source: custom_components/solax_modbus/__init__.py:1059
integration: SolaX Inverter Modbus ([documentation](https://homeassistant-solax-modbus.readthedocs.io/), [issues](https://github.com/wills106/homsassistant-solax-modbus/issues))
First occurred: 4:05:03 PM (94 occurrences)
Last logged: 4:23:39 PM

quickly updating state for computed sensor failed <entity unknown.unknown=unknown> remotecontrol_autorepeat_remaining 0

**Comment by itrankolov** [comment]
I've tried it also, it still gives the error and is still slow to update. 

I figured out something though ... on the systems that it works there is a sensor "sensor.solax_remotecontrol_autorepeat_remaining". Mine does not have that sensor ...

My sensor "sensor.solax_remotecontrol_autorepeat_remaining" was disabled. After enabling the issue is gone!!

**Comment by itrankolov** [comment]
Here is the log after enabling the sensor (temp fix is still in place).

[home-assistant_solax_modbus_2025-08-21T14-33-21.998Z.log](https://github.com/user-attachments/files/21919886/home-assistant_solax_modbus_2025-08-21T14-33-21.998Z.log)

**Comment by gernotgernot** [comment]
I looked for diabled sensor in my solax modbus integration, but i could not find the sensor.solax_remotecontrol_autorepeat_remaining sensor, neither in enabled nor in disabled sensors.....

**Comment by itrankolov** [comment]
Look in the disabled sensors.

<img width="334" height="411" alt="Image" src="https://github.com/user-attachments/assets/ce83bcad-70b4-4dd4-bca3-0b774f5e844b" />

It's name is "Remotecontrol Autorepeat Remaining"

**Comment by infradom** [comment]
> My sensor "sensor.solax_remotecontrol_autorepeat_remaining" was disabled. After enabling the issue is gone!!

Thanks a lot,  now that we understand the root cause, the final solution should be within reach ...


The quickfix was not meant to solve the error, it should solve the slowdown caused by the error (apparently that did not work)

**Comment by gernotgernot** [comment]
> Look in the disabled sensors.
> 
> <img alt="Image" width="334" height="411" src="https://private-user-images.githubusercontent.com/13901389/480560786-ce83bcad-70b4-4dd4-bca3-0b774f5e844b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTU3ODgyMzAsIm5iZiI6MTc1NTc4NzkzMCwicGF0aCI6Ii8xMzkwMTM4OS80ODA1NjA3ODYtY2U4M2JjYWQtNzBiNC00ZGQ0LWJjYTMtMGI3NzRmNWU4NDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwODIxVDE0NTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTVjZTE5OTI2ZDZhY2Y1M2QyN2JmZWQ3Yzc5MTgwZDNkOWQzZGU4MzdkYWU2Y2FjZjNmNDBmMGEyOWEyNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y_iGSpO9d3xwhjiBXezWItUVrw5W2nk_NQ2VA64N54g">
> It's name is "Remotecontrol Autorepeat Remaining"

thanks, i looked before on the same place, but did not see it ;-)
now i found it, error is gone

**Comment by infradom** [comment]
Thanks, I am now submitting a PR that will solve this even if the entity is disabled

**Comment by infradom** [comment]
closing now, should be solved for disabled entities also once the PR is merged and released.
Please reopen if related issues appear

**Comment by itrankolov** [comment]
Your fix does not seem to work. I've patched __init__.py with the updates, but when I disabled sensor.pv_remotecontrol_autorepeat_remaining the error came back.

**Comment by infradom** [comment]
Thanks for testing, but have you tested the fix as published in the PR:
- one additional import line 59 
- one change in line 1055

Or have you tested the previous temporary fix (that did not work)


line 59:
```
from .sensor import SolaXModbusSensor, is_entity_enabled
```

and  line 1055:

```
            if sens and is_entity_enabled(self._hass, self, descr) and not descr.internal: sens.modbus_data_updated() # publish state to GUI and automations faster
```

**Comment by infradom** [comment]
Sorry indeed there is an error in the solution ... I will correct. Thanks and sorry

**Comment by itrankolov** [comment]
I tested the one in the PR :)

**Comment by infradom** [comment]
I had to modify the is_entity_enabled function in sensor.py also. Added to the existing PR
Thanks for testing this !!!!

**Comment by itrankolov** [comment]
Applied the patch to sensor.py as well and it seems to be working as it should. Thanks!

**Comment by infradom** [comment]
Thanks a lot for testing this !
