### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CristiXP** [wills106/homeassistant-solax-modbus#336]
**Describe the bug**

**Mandatory details**
1. Integration Version:2023.02.6
2. HA Version: 2023.2.5
3. Inverter Brand:X3-Hybrid-G4-15.0
4. Plugin Used:Solax Inverter Modbus
5. First 6 digits of Serial:H34A15
6. Connection Method: modbus

Solax house entity sensor.solax_house_load not sure it is displaying the correct value. Can you please check? it seems that the value is increasing once the PV power increases also. Is the version being determined from PV power - injection power or is something read directly from the inverter? 

This is how mine looks daily when production and read from modbus

![image](https://user-images.githubusercontent.com/93781522/220074242-ef04b389-d895-426e-bfa2-6173d27d8785.png)

Versus the one I read from Solax API

![image](https://user-images.githubusercontent.com/93781522/220074616-a4b6f2bb-cf4d-4174-8825-4feb1e55fc16.png)

**Comment by wills106** [comment]
I have just released [2023.03.2b9](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2023.03.2b9) which reintroduces an alternative "House Load Alt" this is using the old calculation.

Let me know if it seems better and doesn't mirror the PC Curve as much.

**Comment by CristiXP** [comment]
Updated, still no change in values.
Solax House is value from API, Solax House Load from moddbus.

![image](https://user-images.githubusercontent.com/93781522/227768762-32441e9a-304b-4246-9b10-4d8e2f83913c.jpeg)

**Comment by CristiXP** [comment]
Seems to be a value next to the correct one. I will keep you posted.![image](https://user-images.githubusercontent.com/93781522/227769068-58866b7d-a798-430b-b7e4-10e08fee85f7.jpeg)
