### ISSUE TITLE
Export value adds additional 0

### ISSUE THREAD

**Issue by SillsHouse** [wills106/homeassistant-solax-modbus#882]
### Describe the bug

Set export value at 9200 it sets 920 in solax modbus. Change this in solax to 9200 it sets 92000 on home assistant
![Screenshot_20240505_085505_SolaxCloud](https://github.com/wills106/homeassistant-solax-modbus/assets/145499880/1b9bf201-508e-4eb1-af58-efb88ad12c3a)
![Screenshot_20240505_085452_Home Assistant](https://github.com/wills106/homeassistant-solax-modbus/assets/145499880/8af7c770-3831-415d-bb60-43119d8a3bf6)

### Integration Version

2024.05.2

### Homeassistant core version

2024.5.1

### Inverter brand

Solax 

### Plugin used

plugin_solax.py

### Serial prefix

H4602A

### Inverter firmware versions

Can't find sorry

### Connection Method

Solax pocket wifi

### Dongle firmware

Wifi 3.

### Detailed Error Log

Na

### Additional context

Na

**Comment by Codiwr** [comment]
I'd noticed this too. Hopefully a simple one to address!

**Comment by SillsHouse** [comment]
There is a change that you can make but you have to add it in to the configuration file and every update you have to add the change.  Its on a lower report about a power factor of 10 error. This has been limiting my export to 920w from 9200w since October. Thought something had failed on a string of my solar panels.  Luckily it's been winter so not much export lost.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wills106** [comment]
Should be corrected in [2024.05.3](https://github.com/wills106/homeassistant-solax-modbus/releases/tag/2024.05.3)

**Comment by wills106** [comment]
Closing down as I believe this is corrected now.

Feel free to reopen if needed.

**Comment by Codiwr** [comment]
Still showing 60,000W on 2024.5.3 after redownloaded and reconfigured
integration despite 6000W set in Solax app.
